### ISSUE TITLE
Importing prop in camery.py

### ISSUE THREAD

**Issue by p-vitt** [UASLab/ImageAnalysis#6]
I want to give your promising scripts a try to create some maps from aerial images, but I can't get it running. It always fails with

    % scripts/process.py --help
    Traceback (most recent call last):
      File "scripts/process.py", line 27, in <module>
        from lib import camera
      File "/Users/petervitt/projects/ImageAnalysis/scripts/lib/camera.py", line 6, in <module>
        from props import getNode
    ModuleNotFoundError: No module named 'props'

So I installed props 0.0.3 via pip, but this module doesn't have a `getNode`. So the question is, which prop module do I need to fulfill the requirements? 

Any help appreciated. Thanks in advance.

**Comment by p-vitt** [comment]
Shame on me, I found the other [Issue](https://github.com/UASLab/ImageAnalysis/issues/4)
