### ISSUE TITLE
No module named libxmp

### ISSUE THREAD

**Issue by p-vitt** [UASLab/ImageAnalysis#7]
Again a missing module that I can't find. Now it says

    % scripts/process.py --help
    Traceback (most recent call last):
      File "scripts/process.py", line 33, in <module>
        from lib import pose
      File "/Users/petervitt/projects/ImageAnalysis/scripts/lib/pose.py", line 16, in <module>
        from . import exif
      File "/Users/petervitt/projects/ImageAnalysis/scripts/lib/exif.py", line 7, in <module>
        from libxmp.utils import file_to_dict
    ModuleNotFoundError: No module named 'libxmp'

pip doesn't know about libxmp, it only has a libxmplite, which doesn't provide the requested modules. There is a libxmp library available on Mac via MacPorts, however, this also doesn't seem to bring along what's needed.

Perhaps it would be nice to add some lines in the README on what stuff is needed. Right now this is what I installed additionally to my existing setup:

    % sudo pip install opencv-contrib-python panda3d numpy tqdm scipy geojson navpy piexif

**Comment by p-vitt** [comment]
Ok, libxmp comes with python-xmp-toolkit, which extends the list to

    % sudo pip install opencv-contrib-python panda3d numpy tqdm scipy geojson navpy piexif python-xmp-toolkit

**Comment by p-vitt** [comment]
`sudo port install exempi` finally makes it run.
